app = "stalk"            # ganti kalau mau nama lain (unik di fly)
primary_region = "sin"   # Singapore biar deket ID

[build]
  builder = "paketobuildpacks/builder:base"

# jalankan sebagai worker (bukan web)
[processes]
  worker = "python main.py"

# matiin service HTTP (kita nggak expose port)
[[vm]]
  size = "shared-cpu-1x"
  memory = 256
